services:
  lightbox:
    build: .
    container_name: immich-lightbox
    restart: unless-stopped
    ports:
      - '7211:7211'
    env_file:
      - .env.local
    volumes:
      - ./content:/app/content:ro
