import { NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'path';
import yaml from 'js-yaml';
import { invalidateConfigCache } from '@/lib/config';
import type { GalleryYaml, SettingsYaml } from '@/lib/config/schema';

const CONTENT_DIR = path.join(process.cwd(), 'content');

export async function POST(request: Request) {
  const body = await request.json().catch(() => ({}));

  if (!body.immichApiUrl || !body.immichApiKey) {
    return NextResponse.json(
      { success: false, error: 'Immich URL and API key are required' },
      { status: 400 },
    );
  }

  try {
    const baseUrl = body.immichApiUrl.replace(/\/+$/, '');
    const apiUrl = baseUrl.match(/\/api\/?$/) ? baseUrl : `${baseUrl}/api`;

    // Build settings.yaml
    const settings: SettingsYaml = {
      title: body.siteTitle || 'My Portfolio',
      subtitle: body.siteSubtitle || '',
      lang: body.lang || 'en',
      seo: {
        title: body.seoTitle || body.siteTitle || 'My Portfolio',
        description: body.seoDescription || '',
        noIndex: body.noIndex === true,
        noFollow: body.noFollow === true,
      },
      exifOnHover: body.exifOnHover !== false,
      map: body.mapEnabled === true,
      transitions: body.transitions !== false,
      theme: {
        preset: body.themePreset || 'studio',
        accent: body.accentColor || '#e60012',
        photoFrame: body.photoFrame || 'passepartout',
        grain: body.grain !== false,
        headerDot: body.headerDot !== false,
        heroStyle: body.heroStyle || 'split',
      },
      grid: {
        columns: body.gridColumns || 3,
        gap: body.gridGap ?? 12,
        aspectRatio: body.gridAspectRatio || '1',
        layout: body.gridLayout || 'masonry',
      },
      ...(body.footerName || body.footerInstagram || body.footerEmail || body.footerWebsite
        ? {
            footer: {
              name: body.footerName || undefined,
              instagram: body.footerInstagram || undefined,
              email: body.footerEmail || undefined,
              website: body.footerWebsite || undefined,
            },
          }
        : {}),
      legal: body.legalEnabled
        ? {
            enabled: true,
            name: body.legalName || '',
            address: body.legalAddress || '',
            zipCity: body.legalZipCity || '',
            country: body.legalCountry || '',
            email: body.legalEmail || undefined,
            phone: body.legalPhone || undefined,
          }
        : { enabled: false, name: '', address: '', zipCity: '', country: '' },
    };

    // Build gallery.yaml
    const gallery: GalleryYaml = {
      hero: body.heroImages || [],
      albums: body.albumIds || [],
    };

    // Build about.md if portrait, name, or bio provided
    const hasAboutData = body.aboutPortrait || body.aboutName || body.aboutBio;
    if (hasAboutData) {
      const gearList = body.aboutGear
        ? body.aboutGear.split('\n').filter((l: string) => l.trim())
        : [];
      const aboutFrontmatter: Record<string, unknown> = {
        portrait: body.aboutPortrait || '',
        name: body.aboutName || '',
        location: body.aboutLocation || '',
        gear: gearList,
      };
      const aboutContent = `---\n${yaml.dump(aboutFrontmatter, { lineWidth: 120, quotingType: '"', noRefs: true, sortKeys: false })}---\n\n${body.aboutBio || ''}\n`;
      await fs.writeFile(path.join(CONTENT_DIR, 'about.md'), aboutContent, 'utf8');
    }

    // Write settings.yaml
    const settingsHeader = '# ── Site Settings ─────────────────────────────────\n';
    const settingsContent =
      settingsHeader +
      yaml.dump(settings, { lineWidth: 120, quotingType: '"', noRefs: true, sortKeys: false });
    await fs.writeFile(path.join(CONTENT_DIR, 'settings.yaml'), settingsContent, 'utf8');

    // Write gallery.yaml
    const galleryHeader = '# ── Gallery Structure ──────────────────────────────\n';
    const galleryContent =
      galleryHeader +
      yaml.dump(gallery, { lineWidth: 120, quotingType: '"', noRefs: true, sortKeys: false });
    await fs.writeFile(path.join(CONTENT_DIR, 'gallery.yaml'), galleryContent, 'utf8');

    // Build .env content
    const envVars: string[] = [
      '# Immich Folio Configuration (generated by Setup Wizard)',
      `IMMICH_API_URL=${apiUrl}`,
      `IMMICH_API_KEY=${body.immichApiKey}`,
      body.authSecret ? `AUTH_SECRET=${body.authSecret}` : '',
      body.adminPassword ? `ADMIN_PASSWORD=${body.adminPassword}` : '',
      body.siteTitle ? `SITE_TITLE=${body.siteTitle}` : '',
      body.siteSubtitle ? `SITE_SUBTITLE=${body.siteSubtitle}` : '',
      `CACHE_TTL=${body.cacheTtl ?? 300}`,
      `RATE_LIMIT_RPM=${body.rateLimitRpm ?? 120}`,
    ].filter(Boolean);
    const envContent = envVars.join('\n') + '\n';

    // Try to write .env.local (works with docker-compose env_file)
    let envWritten = false;
    try {
      const envPath = path.join(process.cwd(), '.env.local');
      await fs.writeFile(envPath, envContent, 'utf8');
      envWritten = true;
    } catch {
      // Non-fatal — may not be writable in Docker
    }

    // Also write content/.env so Docker entrypoint picks up AUTH_SECRET
    try {
      const dotEnvPath = path.join(CONTENT_DIR, '.env');
      await fs.writeFile(dotEnvPath, envContent, 'utf8');
    } catch {
      // Non-fatal
    }

    // Invalidate config cache so next request picks up changes
    invalidateConfigCache();

    return NextResponse.json({
      success: true,
      message: 'Configuration saved successfully.',
      note: envWritten
        ? 'Your settings have been saved. You may need to restart the server.'
        : 'Configuration files saved. Please manually set the environment variables below, then restart your server.',
      envFile: envWritten ? undefined : envContent,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Failed to save configuration';
    console.error('[Install API] Error:', message);
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
